dist: trusty
sudo: required

language: groovy

env:
  global:
    - secure: "iQaQaRa8xgjeb+Ujmclkn1EyyDwkWYob370ICXZxsfMVjlowxgfHXeAqfFejRseSbVer1tV+z+4Qg9vGpwn0et/ZpXwx5oTXJE4ziIIEja089LpkCtDBUGQa54CYZGs8yo72fSLhc17TvPt1eg+Ajb//sSJxa/zZAgdYFqQ3q9DoSjjzaWiJ7m6U0NUqDOZPwSQNonO/IIToTw5OOxIy/YzwtWE66X6K5YyPL4FiPzYUdXMPm/V/jAA4YYNY7ddfNUcA3/vC9ZxD1nT/+PYvKzRcD7fYa9OhKpmfPnLJjO/wSHn8s2KMyNou0HkrkOBVQejdW7kvIBYeyxxZk0/pQKEKyvIvgyVN9Dx0ctsdWED9rPqFAsJowPLSUy707jbUqWft6RAVsf917qdfSWz4/I0RXpXAgn/mEJ0dtOvqs+76950Wu6J92eJxOtP1/sRvgCIgIBFm7UYiyyIjsZhKnatcrm5JgrZpWomkjQWPnfwRjShykB5pC9MzZWl942wvWyChvHJQvl+Id1xCJr5Cwf4bEAy//4HzNIGfe5QBG9Q1YpxYV44xGkbJxJphMVdoyMTCpE9Lg30tpu4i8qVsos0lYmVig3ghHX4Inbk4PwwYYeBFjmoqFRmslMnXQEC3aUWyj2ADAYN8ZHJvniOGkTzXxd172ETrHvSTcAzfCH8="

jdk:
  - oraclejdk8

script:
  - gradle sonarqube

cache:
  directories:
    - '$HOME/.sonar/cache'
