dist: trusty
sudo: required

language: groovy

addons:
  sonarqube:
    token:
      secure: "2yFRZOgcqnyMHi+ljN5e6R5NOkFA7l2LUK9mNMPOS7n8DTqrJxuPQ38WCO5ae93c9CRCJchwGX78TnmnvjFmeFezX+WiZsxHL9IJE30PuTZlxAAuLauKwDOhF0SdwUkTUX2s++LbzUuM/bSHol6aesiFXxPCvqDkRBfaHFEVVR//y0MN3u5rVXU1L2gKmKWv/L+fo+6TDWkD9/zA25din7DVUJes0+FQdjAZpqglOJtXoYh3FjN0h8yzhDvQIcc4yLsFrDrJdZrR/o/9CvIiwyBAi3s/J0ImdWnV/IBoYHhqEE6Rk1TCY/aFrsW/WmE6eKK9B9BHxk3/WKtjR2uXMFqhswSHH8xZkLXS7oKPHeDX3qoizwTqdDT5tjMYudx6Rck4QyTv0lvLyEhPs93Mz4ZUshyFXPCMuKuoEiMbdNqeEi3kfN1fQIFxiWlBhS+jKY6xn1xtM69RzVL3czdq/ydOLkKv4kfW1SWCDghYNf/P6OBKOjSzsHVfaCtxF+6hnl39DdchryWxYt18BNNXUAIjIVrc/k2BHDVlHT5HFN8Y5bK0NeM2ZwcooK7TCuhzMzBthzsuKl7Oe96vWGS7mgDItxfsgWsXXtmzeeoaizWUyzuFbpLKts3Doz6X0p4jLcFtU8qR3RHgC/YnZCeictQD0gT117kvgXOvPOjK5es="

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
